apiVersion: v1
kind: Pod
metadata:
  name: nginx-efs
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: efs-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: efs-volume
    persistentVolumeClaim:
      claimName: efs-claim
